### PR TITLE
python-infomap 2.6.1, add maintainer

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Changes:
- [x] use license from sdist
- [x] tidy up some recipe syntax
- [x] ensure conda-created CLI entry_point
- [x] add `pip` check
- [x] add CLI smoke test 
- [ ] windows?

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge/python-infomap ready for review. Thanks for maintaining this: will try again for windows on a separate PR.

**Comment by TnTo** [comment]
Can I ask to be removed from maintainers' list?
TY

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
Thanks for the speedy response!

> Can I ask to be removed from maintainers' list?

Done. Thank you for all your efforts!

**Comment by bollwyvl** [comment]
@conda-forge/python-infomap Back to green, ready for review.

**Comment by bollwyvl** [comment]
ping @conda-forge/python-infomap . will ask core for help soon.

**Pull request merged**
